using System.Collections.Concurrent;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Rustine.Wpf.Core;

public sealed partial class Log : IDisposable
{
    [System.Runtime.InteropServices.LibraryImport("kernel32.dll")]
    [return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.Bool)]
    private static partial bool AttachConsole(uint dwProcessId);

    const uint ATTACH_PARENT_PROCESS = 0x0ffffffff;

    public enum Severity { Error, Warning, Information, Debug }

    /// <summary>
    /// Represents a log event.
    /// </summary>
    /// <param name="Severity"></param>
    /// <param name="Message"></param>
    /// <param name="Timestamp"></param>
    /// <param name="ThreadName"></param>
    /// <param name="IsExternal">Indicates whether the event was external, i.e. not generated by the application itself.</param>
    public record class Event(Severity Severity, string Message, DateTime Timestamp, string ThreadName, bool IsExternal)
    {
        public override string ToString()
        {
            return ToString(iso8601: true);
        }

        public string ToString(bool iso8601)
        {
            static string SeverityToString(Severity level)
            {
                return level switch
                {
                    Severity.Error => "ERROR",
                    Severity.Warning => "WARNING",
                    Severity.Information => "INFO",
                    Severity.Debug => "DEBUG",
                    _ => "UNKNOWN",
                };
            }

            string iso8601Timestamp = Timestamp.ToString("o", CultureInfo.InvariantCulture);
            return $"[{ThreadName}] [{(iso8601 ? iso8601Timestamp : Timestamp)}] [{SeverityToString(Severity)}] {Message}";
        }
    }

    public delegate void LogEventHandler(Event logEvent);

    bool isDisposed;

    readonly ConcurrentDictionary<string, Logger> loggers = [];
    readonly ConcurrentDictionary<int, string> threadNames = [];

    public event LogEventHandler? Appended;

    public long MaximumFileSize { get; set; } = 10 * 1024 * 1024 /* 10 MB */;

    public string Path { get; } = string.Empty;

    /// <summary>
    /// Creates a new instance of <see cref="Log"/>.
    /// </summary>
    public Log()
    {
        RegisterCurrentThreadName("Main");

        AttachConsole(ATTACH_PARENT_PROCESS);
    }

    public void Dispose()
    {
        if (!isDisposed)
        {
            isDisposed = true;
        }
    }

    public Logger GetLogger<T>(bool enableTypeName = true, bool enableCallerName = true)
    {
        return GetLogger(typeof(T).Name, enableTypeName, enableCallerName);
    }

    public Logger GetLogger(string name, bool enableTypeName = true, bool enableCallerName = true)
    {
        if (loggers.TryGetValue(name, out Logger? logger))
        {
            return logger;
        }

        logger = new Logger(this, name, enableTypeName, enableCallerName);
        _ = loggers.TryAdd(name, logger);
        return logger;
    }

    /// <summary>
    /// Registers a name for the current thread.
    /// </summary>
    /// <param name="name"></param>
    public void RegisterCurrentThreadName(string name)
    {
        int threadId = Environment.CurrentManagedThreadId;
        _ = threadNames.TryAdd(threadId, name);
    }

    /// <summary>
    /// Logs a message to the global application log.
    /// Use <see cref="GetLogger"/> to get a instance of <see cref="Logger"/> which can be easier to use.
    /// </summary>
    public void Append(Severity severity, string message, string typeName = "", [CallerMemberName] string callerName = "")
    {
        Event ev = new(
            Severity: severity,
            Message: SynthesizeMessage(message, typeName, callerName),
            Timestamp: DateTime.Now,
            ThreadName: threadNames.TryGetValue(Environment.CurrentManagedThreadId, out string? threadName) ? threadName : $"{Environment.CurrentManagedThreadId}",
            IsExternal: false);

        Append(ev);
    }

    /// <summary>
    /// Synthesizes a log message from the provided components. <br/>
    /// If both <paramref name="typeName"/> and <paramref name="callerName"/> are provided, the format will be: <br/>
    /// {typeName}::{callerName} {message} <br/>
    /// If only <paramref name="typeName"/> is provided, the format will be: <br/>
    /// {typeName} {message} <br/>
    /// If only <paramref name="callerName"/> is provided, the format will be: <br/>
    /// {callerName} {message} <br/>
    /// If neither is provided, the format will be: <br/>
    /// {message}
    /// </summary>
    /// <param name="message"></param>
    /// <param name="typeName"></param>
    /// <param name="callerName"></param>
    public static string SynthesizeMessage(string message, string typeName, string callerName)
    {
        const string TypedCallerFormat = "{0}::{1} {2}";
        const string TypedFormat = "{0} {1}";
        const string PlainFormat = "{0}";

        string logMsg = (string.IsNullOrEmpty(typeName), string.IsNullOrEmpty(callerName)) switch
        {
            (true, true) => string.Format(CultureInfo.InvariantCulture, PlainFormat, message),
            (true, false) => string.Format(CultureInfo.InvariantCulture, TypedFormat, callerName, message),
            (false, true) => string.Format(CultureInfo.InvariantCulture, TypedFormat, typeName, message),
            (false, false) => string.Format(CultureInfo.InvariantCulture, TypedCallerFormat, typeName, callerName, message),
        };
        return logMsg;
    }

    /// <summary>
    /// Logs an event to the global application log.
    /// </summary>
    /// <param name="ev"></param>
    public void Append(Event ev)
    {
        // Console
        {
            var previousColor = Console.ForegroundColor;
            Console.ForegroundColor = ev.Severity switch
            {
                Severity.Error => ConsoleColor.Red,
                Severity.Warning => ConsoleColor.Yellow,
                Severity.Information => ConsoleColor.White,
                Severity.Debug => ConsoleColor.Blue,
                _ => previousColor,
            };
            Console.WriteLine(ev.ToString(iso8601: false));
            Console.ForegroundColor = previousColor;
        }

        // Event
        try
        {
            Appended?.Invoke(ev);
        }
        catch (Exception e)
        {
            Console.WriteLine(string.Format(CultureInfo.InvariantCulture, "{0}::{1} {2}", nameof(Log), nameof(Append), e.Message));
        }
    }
}

public class Logger(Log applicationLog, string typeName, bool enableTypeName = true, bool enableCallerName = true)
{
    readonly Log log = applicationLog;
    readonly string typeName = typeName;
    readonly bool enableTypeName = enableTypeName;
    readonly bool enableCallerName = enableCallerName;

    /// <summary>
    /// Logs an error message.
    /// </summary>
    /// <param name="message"></param>
    /// <param name="callerName"></param>
    public void Error(string message = "", [CallerMemberName] string callerName = "")
    {
        log.Append(Log.Severity.Error, message, enableTypeName ? typeName : string.Empty, enableCallerName ? callerName : string.Empty);
    }

    /// <summary>
    /// Logs a warning message.
    /// </summary>
    /// <param name="message"></param>
    /// <param name="callerName"></param>
    public void Warning(string message = "", [CallerMemberName] string callerName = "")
    {
        log.Append(Log.Severity.Warning, message, enableTypeName ? typeName : string.Empty, enableCallerName ? callerName : string.Empty);
    }

    /// <summary>
    /// Logs an information message.
    /// </summary>
    /// <param name="message"></param>
    /// <param name="callerName"></param>
    public void Info(string message = "", [CallerMemberName] string callerName = "")
    {
        log.Append(Log.Severity.Information, message, enableTypeName ? typeName : string.Empty, enableCallerName ? callerName : string.Empty);
    }

    /// <summary>
    /// Logs a debug message.
    /// </summary>
    /// <param name="message"></param>
    /// <param name="callerName"></param>
    public void Debug(string message = "", [CallerMemberName] string callerName = "")
    {
        log.Append(Log.Severity.Debug, message, enableTypeName ? typeName : string.Empty, enableCallerName ? callerName : string.Empty);
    }
}