using System.Collections.Concurrent;
using System.Globalization;

namespace Rustine.Wpf.Core;

public sealed partial class Log : IDisposable
{
    [System.Runtime.InteropServices.LibraryImport("kernel32.dll")]
    [return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.Bool)]
    private static partial bool AttachConsole(uint dwProcessId);

    const uint ATTACH_PARENT_PROCESS = 0x0ffffffff;

    public enum Severity { Error, Warning, Information, Debug }

    /// <summary>
    /// Represents a log event.
    /// </summary>
    /// <param name="Severity"></param>
    /// <param name="Message"></param>
    /// <param name="Timestamp"></param>
    /// <param name="ThreadName"></param>
    /// <param name="IsExternal">Indicates whether the event was external, i.e. not generated by the application itself.</param>
    public record class Event(Severity Severity, string Message, DateTime Timestamp, string ThreadName)
    {
        public override string ToString()
        {
            return ToString(iso8601: true);
        }

        public string ToString(bool iso8601)
        {
            static string SeverityToString(Severity level)
            {
                return level switch
                {
                    Severity.Error => "R",
                    Severity.Warning => "W",
                    Severity.Information => "I",
                    Severity.Debug => "D",
                    _ => throw new ArgumentOutOfRangeException(nameof(level), "Unknown severity level"),
                };
            }

            string iso8601Timestamp = $" [{Timestamp.ToString("o", CultureInfo.InvariantCulture)}] ";
            return $"[{ThreadName}]{(iso8601 ? iso8601Timestamp : "")}[{SeverityToString(Severity)}] {Message}";
        }
    }

    public delegate void LogEventHandler(Event logEvent);

    bool isDisposed;

    // Named thread registry
    readonly ConcurrentDictionary<int, string> threadNames = [];

    // Listener registry
    readonly ConcurrentDictionary<ILogListener, byte> listeners = new();

    /// <summary>
    /// Creates a new instance of <see cref="Log"/>.
    /// </summary>
    public Log()
    {
        RegisterCurrentThreadName("Main");

        AttachConsole(ATTACH_PARENT_PROCESS);

        // Register default console listener
        AddListener(new ConsoleLogListener());
    }

    public void Dispose()
    {
        if (!isDisposed)
        {
            isDisposed = true;
        }
    }

    // Listener management
    public void AddListener(ILogListener listener)
    {
        listeners.TryAdd(listener, 0);
    }

    /// <summary>
    /// Registers a name for the current thread.
    /// </summary>
    /// <param name="name"></param>
    public void RegisterCurrentThreadName(string name)
    {
        int threadId = Environment.CurrentManagedThreadId;
        _ = threadNames.TryAdd(threadId, name);
    }

    /// <summary>
    /// Logs a message to the global application log.
    /// Use <see cref="GetLogger"/> to get a instance of <see cref="Logger"/> which can be easier to use.
    /// </summary>
    public void Append(Severity severity, string message, string typeName)
    {
        Event ev = new(
            Severity: severity,
            Message: $"{typeName} {message}",
            Timestamp: DateTime.Now,
            ThreadName: threadNames.TryGetValue(Environment.CurrentManagedThreadId, out string? threadName) ? threadName : $"{Environment.CurrentManagedThreadId}");

        Append(ev);
    }

    /// <summary>
    /// Logs an event to the global application log.
    /// </summary>
    /// <param name="ev"></param>
    public void Append(Event ev)
    {
        // Dispatch to listeners
        foreach (var listener in listeners.Keys)
        {
            try { listener.OnLog(ev); }
            catch { /* swallow listener exceptions to not block logging */ }
        }
    }

    // Convenience methods mirroring severity-specific logging used previously
    public void Error<T>(string message)
        => Append(Severity.Error, message, typeof(T).Name);

    public void Warning<T>(string message)
        => Append(Severity.Warning, message, typeof(T).Name);

    public void Info<T>(string message)
        => Append(Severity.Information, message, typeof(T).Name);

    public void Debug<T>(string message)
        => Append(Severity.Debug, message, typeof(T).Name);
}

// Listener contract and default console implementation
public interface ILogListener
{
    void OnLog(Log.Event ev);
}

public sealed class ConsoleLogListener : ILogListener
{
    public void OnLog(Log.Event ev)
    {
        var previousColor = Console.ForegroundColor;
        Console.ForegroundColor = ev.Severity switch
        {
            Log.Severity.Error => ConsoleColor.Red,
            Log.Severity.Warning => ConsoleColor.Yellow,
            Log.Severity.Information => ConsoleColor.White,
            Log.Severity.Debug => ConsoleColor.Blue,
            _ => previousColor,
        };
        Console.WriteLine(ev.ToString(iso8601: false));
        Console.ForegroundColor = previousColor;
    }
}